server:
  port: 8080

spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


logging:
  level:
    com.tfg.cryptoosint: INFO
  file:
    name: logs/crypto-osint-tracker.log

http:
  logging:
    file:
      name: logs/http-traffic.log
    max-body-length: 10000
app:
  openapi:
    title: Crypto OSINT Tracker API
    description: API para trazado de wallets y análisis OSINT sobre transacciones Bitcoin
    version: 1.0.0
    contact:
      name: TFG - Antonio Gómez Barranco
      email: gomez.barranco.antonio@gmail.com
      url: https://github.com/AntonioGoBa/crypto-osint-tracker
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html